exports.faceStyles = function(req, res) {
    var context = {
        royalF: [
            {name: "Pink Bean Face", image: "pinkbeanface1"},
            {name: "Dr. Jang Face", image: "drjangface1"},
            {name: "Marble Eyes", image: "marbleeyes1"},
            {name: "Pure Gaze", image: "puregaze1"},
            {name: "Puppy-Eyed Face", image: "puppyeyedface1"},
            {name: "Bulbous-Eyed Face", image: "bulbouseyedface1"}
        ],
        royalM: [
            {name: "Pink Bean Face", image: "pinkbeanface2"},
            {name: "Naricain Face", image: "naricainface1"},
            {name: "Marble Eyes", image: "marbleeyes2"},
            {name: "Glancing Face", image: "glancingface1"},
            {name: "Puppy Eyes Face", image: "puppyeyesface1"},
            {name: "Come On Over Face", image: "comeonoverface1"}
        ],
        ariantF: [
            {name: "Look of Death", image: "lookofdeath1"},
            {name: "Defiant Face", image: "defiantface1"},
            {name: "Intelligent Face", image: "intelligentface1"},
            {name: "Strong Stare", image: "strongstare1"},
            {name: "Pucker Up Face", image: "puckerupface1"},
            {name: "Soul's Window", image: "soulswindow1"}
        ],
        ariantM: [
            {name: "Insomniac Daze", image: "insomniacdaze1"},
            {name: "Defiant Face", image: "defiantface2"},
            {name: "Prudent Face", image: "prudentface2"},
            {name: "Rebel's Fire", image: "rebelsfire1"},
            {name: "Alert Face", image: "alertface1"},
            {name: "Curious Dog", image: "curiousdog1"}
        ],
        amoriaF: [
            {name: "Athena's Grace", image: "athenasgrace1"},
            {name: "Hera's Radiance", image: "herasradiance1"},
            {name: "Prudent Face", image: "prudentface1"},
            {name: "Intelligent Face", image: "intelligentface1"},
            {name: "Strong Stare", image: "strongstare1"},
            {name: "Angel Glow", image: "angelglow1"},
            {name: "Babyface Pout", image: "babyfacepout1"},
            {name: "Pucker Up Face", image: "puckerupface1"},
            {name: "Dollface Look", image: "dollfacelook1"},
            {name: "Soul's Window", image: "soulswindow1"}
        ],
        amoriaM: [
            {name: "Champion Focus", image: "championfocus1"},
            {name: "Irritable Face", image: "irritableface1"},
            {name: "Defiant Face", image: "defiantface2"},
            {name: "Confident Face", image: "confidentface1"},
            {name: "Dramatic Face", image: "dramaticface1"},
            {name: "Rebel's Fire", image: "rebelsfire1"},
            {name: "Alert Face", image: "alertface1"},
            {name: "Babyface Pout", image: "babyfacepout2"},
            {name: "Sad Innocence", image: "sadinnocence1"},
            {name: "Worrisome Glare", image: "worrisomeglare1"}
        ],
        henesysF: [
            {name: "Defiant Face", image: "defiantface1"},
            {name: "Prudent Face", image: "prudentface1"},
            {name: "Intelligent Face", image: "intelligentface1"},
            {name: "Strong Stare", image: "strongstare1"},
            {name: "Angel Glow", image: "angelglow1"},
            {name: "Babyface Pout", image: "babyfacepout1"},
            {name: "Pucker Up Face", image: "puckerupface1"},
            {name: "Dollface Look", image: "dollfacelook1"},
            {name: "Hopeless Gaze", image: "hopelessgaze1"},
            {name: "Soul's Window", image: "soulswindow1"},
            {name: "Curious Look", image: "curiouslook1"},
            {name: "Wide-Eyed Girl", image: "wideeyedgirl1"},
            {name: "Innocent Look", image: "innocentlook1"},
            {name: "Tender Love", image: "tenderlove1"}
        ],
        henesysM: [
            {name: "Defiant Face", image: "defiantface2"},
            {name: "Confident Face", image: "confidentface1"},
            {name: "Prudent Face", image: "prudentface2"},
            {name: "Dramatic Face", image: "dramaticface1"},
            {name: "Rebel's Fire", image: "rebelsfire1"},
            {name: "Alert Face", image: "alertface1"},
            {name: "Babyface Pout", image: "babyfacepout2"},
            {name: "Sad Innocence", image: "sadinnocence1"},
            {name: "Worrisome Glance", image: "worrisomeglare1"},
            {name: "Curious Dog", image: "curiousdog1"},
            {name: "Look of Wonder", image: "lookofwonder1"},
            {name: "Eye of the Lion", image: "eyeofthelion1"},
            {name: "Child's Play", image: "childsplay1"},
            {name: "Sarcastic Face", image: "sarcasticface1"}
        ],
        nlcF: [
            {name: "Beauty Stare", image: "beautystare1"},
            {name: "Prudent Face", image: "prudentface1"},
            {name: "Intelligent Face", image: "intelligentface1"},
            {name: "Strong Stare", image: "strongstare1"},
            {name: "Angel Glow", image: "angelglow1"},
            {name: "Babyface Pout", image: "babyfacepout1"},
            {name: "Pucker Up Face", image: "puckerupface1"},
            {name: "Hopeless Gaze", image: "hopelessgaze1"},
            {name: "Soul's Window", image: "soulswindow1"}
        ],
        nlcM: [
            {name: "Curious Dog", image: "curiousdog1"},
            {name: "Defiant Face", image: "defiantface2"},
            {name: "Confident Face", image: "confidentface1"},
            {name: "Prudent Face", image: "prudentface2"},
            {name: "Dramatic Face", image: "dramaticface1"},
            {name: "Rebel's Fire", image: "rebelsfire1"},
            {name: "Alert Face", image: "alertface1"},
            {name: "Babyface Pout", image: "babyfacepout2"},
            {name: "Worrisome Glance", image: "worrisomeglare1"}
        ],
        orbisF: [
            {name: "Defiant Face", image: "defiantface1"},
            {name: "Prudent Face", image: "prudentface1"},
            {name: "Intelligent Face", image: "intelligentface1"},
            {name: "Strong Stare", image: "strongstare1"},
            {name: "Angel Glow", image: "angelglow1"},
            {name: "Babyface Pout", image: "babyfacepout1"},
            {name: "Pucker Up Face", image: "puckerupface1"},
            {name: "Dollface Look", image: "dollfacelook1"},
            {name: "Hopeless Gaze", image: "hopelessgaze1"},
            {name: "Soul's Window", image: "soulswindow1"},
            {name: "Curious Look", image: "curiouslook1"},
            {name: "Innocent Look", image: "innocentlook1"},
            {name: "Tender Love", image: "tenderlove1"}
        ],
        orbisM: [
            {name: "Defiant Face", image: "defiantface2"},
            {name: "Confident Face", image: "confidentface1"},
            {name: "Prudent Face", image: "prudentface2"},
            {name: "Dramatic Face", image: "dramaticface1"},
            {name: "Rebel's Fire", image: "rebelsfire1"},
            {name: "Alert Face", image: "alertface1"},
            {name: "Babyface Pout", image: "babyfacepout2"},
            {name: "Sad Innocence", image: "sadinnocence1"},
            {name: "Worrisome Glare", image: "worrisomeglare1"},
            {name: "Curious Dog", image: "curiousdog1"},
            {name: "Look of Wonder", image: "lookofwonder1"},
            {name: "Child's Play", image: "childsplay1"},
            {name: "Sarcastic Face", image: "sarcasticface1"}
        ],
        ludiF: [
            {name: "Defiant Face", image: "defiantface1"},
            {name: "Prudent Face", image: "prudentface1"},
            {name: "Intelligent Face", image: "intelligentface1"},
            {name: "Strong Stare", image: "strongstare1"},
            {name: "Angel Glow", image: "angelglow1"},
            {name: "Babyface Pout", image: "babyfacepout1"},
            {name: "Pucker Up Face", image: "puckerupface1"},
            {name: "Dollface Look", image: "dollfacelook1"},
            {name: "Hopeless Gaze", image: "hopelessgaze1"},
            {name: "Soul's Window", image: "soulswindow1"},
            {name: "Curious Look", image: "curiouslook1"},
            {name: "Wisdom Glance", image: "wisdomgaze1"}
        ],
        ludiM: [
            {name: "Defiant Face", image: "defiantface2"},
            {name: "Confident Face", image: "confidentface1"},
            {name: "Prudent Face", image: "prudentface2"},
            {name: "Dramatic Face", image: "dramaticface1"},
            {name: "Rebel's Fire", image: "rebelsfire1"},
            {name: "Alert Face", image: "alertface1"},
            {name: "Babyface Pout", image: "babyfacepout2"},
            {name: "Sad Innocence", image: "sadinnocence1"},
            {name: "Worrisome Glance", image: "worrisomeglare1"},
            {name: "Curious Dog", image: "curiousdog1"},
            {name: "Look of Wonder", image: "lookofwonder1"},
            {name: "Cool Guy Gaze", image: "coolguygaze1"}
        ],
        mulungF: [
            {name: "Hypnotized Look", image: "hypnotizedlook1"},
            {name: "Defiant Face", image: "defiantface1"},
            {name: "Intelligent Face", image: "intelligentface1"},
            {name: "Strong Stare", image: "strongstare1"},
            {name: "Babyface Pout", image: "babyfacepout1"},
            {name: "Pucker Up Face", image: "puckerupface1"},
            {name: "Hopeless Gaze", image: "hopelessgaze1"},
            {name: "Soul's Window", image: "soulswindow1"},
            {name: "Look Of Death", image: "lookofdeath1"},
            {name: "Innocent Look", image: "innocentlook1"},
            {name: "Tender Love", image: "tenderlove1"}
        ],
        mulungM: [
            {name: "Defiant Face", image: "defiantface2"},
            {name: "Confident Face", image: "confidentface1"},
            {name: "Prudent Face", image: "prudentface2"},
            {name: "Rebel's Fire", image: "rebelsfire1"},
            {name: "Alert Face", image: "alertface1"},
            {name: "Babyface Pout", image: "babyfacepout2"},
            {name: "Sad Innocence", image: "sadinnocence1"},
            {name: "Curious Dog", image: "curiousdog1"},
            {name: "Smart Aleck", image: "smartaleck1"},
            {name: "Child's Play", image: "childsplay1"},
            {name: "Sarcastic Face", image: "sarcasticface1"}
        ],
        edelF: [
            {name: "Defiant Face", image: "defiantface1"},
            {name: "Prudent Face", image: "prudentface1"},
            {name: "Intelligent Face", image: "intelligentface1"},
            {name: "Strong Stare", image: "strongstare1"},
            {name: "Angel Glow", image: "angelglow1"},
            {name: "Babyface Pout", image: "babyfacepout1"},
            {name: "Pucker Up Face", image: "puckerupface1"},
            {name: "Dollface Look", image: "dollfacelook1"},
            {name: "Hopeless Gaze", image: "hopelessgaze1"},
            {name: "Soul's Window", image: "soulswindow1"},
            {name: "Curious Look", image: "curiouslook1"},
            {name: "Beauty Stare", image: "beautystare1"},
            {name: "Gentle Glow", image: "gentleglow1"},
            {name: "Demure Poise Eyes", image: "demurepoiseeyes1"},
            {name: "Wide-Eyed Girl", image: "wideeyedgirl1"},
            {name: "Compassion Look", image: "compassionlook1"},
            {name: "Innocent Look", image: "innocentlook1"},
            {name: "Lazy Look", image: "lazylook1"},
            {name: "Tender Love", image: "tenderlove1"},
            {name: "Glamorous Edge", image: "glamorousedge1"},
            {name: "Kitty Cat", image: "kittycat1"}
        ],
        edelM: [
            {name: "Defiant Face", image: "defiantface2"},
            {name: "Confident Face", image: "confidentface1"},
            {name: "Prudent Face", image: "prudentface2"},
            {name: "Dramatic Face", image: "dramaticface1"},
            {name: "Rebel's Fire", image: "rebelsfire1"},
            {name: "Alert Face", image: "alertface1"},
            {name: "Babyface Pout", image: "babyfacepout2"},
            {name: "Sad Innocence", image: "sadinnocence1"},
            {name: "Worrisome Glare", image: "worrisomeglare1"},
            {name: "Curious Dog", image: "curiousdog1"},
            {name: "Look of Wonder", image: "lookofwonder1"},
            {name: "Ghost Face Stare", image: "ghostfacestare1"},
            {name: "Fierce Edge", image: "fierceedge1"},
            {name: "Demure Poise", image: "demurepoise1"},
            {name: "Insomniac Daze", image: "insomniacdaze1"},
            {name: "Child's Play", image: "childsplay1"},
            {name: "Edge of Emotion", image: "edgeofemotion1"},
            {name: "Pensive Look", image: "pensivelook1"},
            {name: "Sarcastic Face", image: "sarcasticface1"},
            {name: "Shade of Cool", image: "shadeofcool1"},
            {name: "Fearful Glance", image: "fearfulglance1"}
        ],
        showaF: [
            {name: "Compassion Look", image: "compassionlook1"},
            {name: "Defiant Face", image: "defiantface1"},
            {name: "Intelligent Face", image: "intelligentface1"},
            {name: "Strong Stare", image: "strongstare1"},
            {name: "Pucker Up Face", image: "puckerupface1"},
            {name: "Soul's Window", image: "soulswindow1"}
        ],
        showaM: [
            {name: "Fierce Edge", image: "fierceedge1"},
            {name: "Defiant Face", image: "defiantface2"},
            {name: "Prudent Face", image: "prudentface2"},
            {name: "Rebel's Fire", image: "rebelsfire1"},
            {name: "Alert Face", image: "alertface1"},
            {name: "Curious Dog", image: "curiousdog1"}
        ],
        cbdF: [
            {name: "Compassion Look", image: "compassionlook1"},
            {name: "Hypnotized Look", image: "hypnotizedlook1"},
            {name: "Look of Death", image: "lookofdeath1"},
            {name: "Shuteye", image: "shuteye1"},
            {name: "Pucker Up Face", image: "puckerupface1"},
            {name: "Soul's Window", image: "soulswindow1"}
        ],
        cbdM: [
            {name: "Fierce Edge", image: "fierceedge1"},
            {name: "Insomniac Daze", image: "insomniacdaze1"},
            {name: "Overjoyed Smile", image: "overjoyedsmile1"},
            {name: "Shuteye", image: "shuteye2"},
            {name: "Alert Face", image: "alertface1"},
            {name: "Curious Dog", image: "curiousdog1"}
        ]
    };
    context.title = "MapleNow - Plastic Surgery";
    res.render('face', context);
}
